version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 25
    versioning-strategy: increase
    allow:
      - dependency-name: "@nestia/*"
      - dependency-name: "typia"
      - dependency-name: "tgrid"
      - dependency-name: "typescript"
      - dependency-name: "typescript-transform-paths"
      - dependency-name: "ts-patch"
    groups:
      Samchon:
        patterns:
          - "@nestia/*"
          - "typia"
          - "tgrid"
      TypeScript:
        patterns:
          - "typescript"
          - "typescript-transform-paths"
          - "ts-patch"