version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
    versioning-strategy: increase
    allow:
      - dependency-name: "@nestia/*"
      - dependency-name: "@ttsc/*"
      - dependency-name: "tgrid"
      - dependency-name: "ttsc"
      - dependency-name: "typia"
      - dependency-name: "typescript"
    groups:
      Samchon:
        patterns:
          - "@nestia/*"
          - "@ttsc/*"
          - "tgrid"
          - "ttsc"
          - "typia"
      TypeScript:
        patterns:
          - "typescript"
